# Generated by Django 3.1.4 on 2021-05-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=30)),
                ('PatientEmail', models.EmailField(max_length=30)),
                ('PatientPhone', models.CharField(max_length=13)),
                ('AppointmentDate', models.DateField()),
                ('Message', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Message', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_name', models.CharField(max_length=30)),
                ('doctor_name', models.CharField(max_length=30)),
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicines', models.CharField(max_length=30)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_v3.appointment')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_v3.department')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_v3.department'),
        ),
    ]
